
package gheldd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Weather", targetNamespace = "http://gheldd/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Weather {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://gheldd/Weather/getTemperatureRequest", output = "http://gheldd/Weather/getTemperatureResponse")
    public int getTemperature(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://gheldd/Weather/getRainRequest", output = "http://gheldd/Weather/getRainResponse")
    public String getRain(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
